version: '3'

services:

  postgres:
      image: postgres:9.6.20-alpine
      hostname: my-platform-postgres
      networks: 
        - my-platform-net    
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
      volumes:
        - ./postgres_data:/var/lib/postgresql/data        
      ports:
        - 5432:5432

  keycloak:
      image: jboss/keycloak:12.0.1
      hostname: my-platform-keycloak
      networks: 
        - my-platform-net
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: postgres
        DB_SCHEMA: public
        DB_PASSWORD: password
        #KEYCLOAK_USER: admin
        #KEYCLOAK_PASSWORD: admin
        #KEYCLOAK_IMPORT: /imports/realm-export.json
        #Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      volumes:
        - ./keycloak_data/imports:/imports
      ports:
        - 8080:8080
      depends_on:
        - postgres

  redis:
      image: redis:6.2-rc3-alpine
      hostname: my-platform-redis
      command: redis-server --requirepass secret
      ports:
        - "6379:6379" 

  zookeeper:
      image: confluentinc/cp-zookeeper:6.0.2
      hostname: my-platform-zookeeper
      networks: 
        - my-platform-net
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

  kafka:
      image: confluentinc/cp-kafka:6.0.2
      hostname: my-platform-kafka
      networks: 
        - my-platform-net
      depends_on:
        - zookeeper
      ports:
        - 9092:9092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
      image: obsidiandynamics/kafdrop:3.27.0
      hostname: my-platform-kafdrop
      networks: 
        - my-platform-net
      depends_on:
        - kafka
      ports:
        - 19000:9000
      environment:
        KAFKA_BROKERCONNECT: kafka:29092

networks: 
    my-platform-net:
      driver: bridge  


